### PR TITLE
selftesting-shield: release board design files

### PR DESCRIPTION
**Pull request by maribu**
This releases all the design files needed to reproduce or modify the Peripheral Selftesting Shield using KiCAD 7.x

### CODE REVIEW

**Comment by maribu** [comment]
Maybe it makes sense to have a `Licenses` folder and have a copy of the license text of each used license there, rather than having any KiCAD project added here having a copy of the same license?

**Comment by emmanuelsearch** [comment]
Nice! Does it make sense to also add a photo of the thing eg in the Readme?

**Comment by maribu** [comment]
Done. Should be good to go now :)

**Review by emmanuelsearch — APPROVED** [review]
Looks great!

**Pull request merged**
