### PR TITLE
olimex-msp430-arduino-uno: Add adapter for Olimex MSP430 Header boards

### PR DESCRIPTION
**Pull request by maribu**
This is an Adapter PCB that allows connecting Arduino UNO shields to [Olimex MSP430 header boards][1]. It adds an UART-USB adapter, a reset button, and an external resistor for the DCO clock source ($R_{OSC}$ in the datasheet).

[1]: https://www.olimex.com/Products/MSP430/Header/

### CODE REVIEW

**Comment by emmanuelsearch** [comment]
Same suggestion as for [PR1](https://github.com/RIOT-OS/RIOT-Open-Hardware/pull/1) ;)
(about beautifying the Readme with a nice pic of your piece of hardware).

**Comment by maribu** [comment]
Done. I also fixed the `COPYRIGHT.md`, in which I originally forgot that the Arduino UNO shield footprint was taking from https://github.com/Alarm-Siren/arduino-kicad-library and not my own work. Now this should be fine license-wise.

**Comment by maribu** [comment]
Note: Ideally this should not be merged before PR1, as PR1 adds the licenses verbatim text the COPYRIGHT.md refers to.

**Review by emmanuelsearch — APPROVED** [review]
Looks good. Go!

**Comment by maribu** [comment]
Ah, I forgot to state that the RIOT logo has a separate copyright/license and does not fall under "the rest is all mine" statement :sweat_smile:

https://github.com/RIOT-OS/RIOT-Open-Hardware/pull/3 fixes the issue

**Pull request merged**
